- hosts: localhost
  gather_facts: false
  vars:
   - project: "mm-3scale-amp-2"
   - redis_name: "backend-redis"

  tasks:

  - block:

    - name: Switch to project {{ project }}
      command: "oc project {{ project }}"
      changed_when: false

    - name: Scale down existing redis instance and delete the dc
      shell: |
        oc scale --replicas=0 dc {{ redis_name }}
        oc delete dc,svc {{ redis_name }}

    - name: Create the bootstrap master and sentinel
      shell: |
        oc process -f templates/redis-master.yml \
          -p REDIS_MASTER_NAME={{ redis_name }}-master \
          -p REDIS_SENTINEL_NAME={{ redis_name }}-sentinel \
          | oc create -f -

    - name: Scale down existing redis instance and delete the dc
      shell: |
        oc scale --replicas=0 dc {{ redis_name }}
        oc delete dc,svc {{ redis_name }}